# ==========================================
# STAGE 1: INSTALL DEPENDENCIES (The "deps" stage)
# ==========================================

# Use the official Node.js version 22 image based on Alpine Linux.
# "Alpine" is a super tiny version of Linux (only ~5MB), which keeps our image small.
# We name this stage "deps" so we can refer back to it later.
FROM node:22-alpine AS deps

# Set the working directory inside the mini-computer to a folder called /app
WORKDIR /app

# Copy ONLY the package.json and package-lock.json from your laptop into the /app folder.
# We do this first because Docker caches layers. If you change your code but don't change
# your dependencies, Docker skips the npm install step to save time!
COPY package.json package-lock.json ./

# Run `npm ci` (Clean Install). It strictly installs exact versions from package-lock.json.
RUN npm ci


# ==========================================
# STAGE 2: BUILD THE APP (The "builder" stage)
# ==========================================

# Start a brand new, fresh Alpine Linux container and name it "builder"
FROM node:22-alpine AS builder

# Set the working directory to /app
WORKDIR /app

# This is the magic of multi-stage builds!
# We copy the fully installed `node_modules` folder from the "deps" stage into this new stage.
COPY --from=deps /app/node_modules ./node_modules

# Now, copy the rest of your actual source code (components, src, etc.) into the container.
COPY . .

# Generate the Prisma Client so Prisma knows about your database schema.
RUN npx prisma generate

# Compile the Next.js app! Because we enabled output: "standalone" in next.config.ts,
# this command creates a special folder (.next/standalone) that contains ONLY
# the files absolutely necessary to run the server in production.
RUN npm run build


# ==========================================
# STAGE 3: PRODUCTION SERVER (The "runner" stage)
# ==========================================

# Start a final, fresh Alpine Linux container named "runner"
FROM node:22-alpine AS runner

# Set the working directory to /app
WORKDIR /app

# Tell Node.js and Next.js we are running in production mode. This makes them run much faster.
ENV NODE_ENV production
# Tell the app to listen on port 3000
ENV PORT 3000

# Copy the public folder (images, fonts, favicon) from the builder stage
COPY --from=builder /app/public ./public

# Copy the prisma folder (so the server has access to migrations and schema)
COPY --from=builder /app/prisma ./prisma

# Copy the highly-optimized "standalone" server folder generated in Stage 2
COPY --from=builder /app/.next/standalone ./

# Copy the static assets (CSS, JS bundles) generated by Next.js
COPY --from=builder /app/.next/static ./.next/static

# Open port 3000 so the outside world (or Azure) can connect to the Next.js server
EXPOSE 3000

# When the container finally turns on, what command should it run?
# 1. Run `npx prisma migrate deploy` to ensure the Azure database schema is fully up-to-date.
# 2. If the migrations succeed (&&), start the Next.js standalone server using `node server.js`.
CMD ["sh", "-c", "npx prisma migrate deploy && node server.js"]
